# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# MkDocs: https://www.mkdocs.org/
# Material for MkDocs: https://squidfunk.github.io/mkdocs-material/

# To install:
# pip install mkdocs-material

# To run the preview server:
# mkdocs serve

---
site_name: TagStudio
site_description: "A User-Focused Photo & File Management System"
site_url: https://docs.tagstud.io/
repo_url: https://github.com/TagStudioDev/TagStudio
edit_uri: blob/main/docs/
repo_name: TagStudioDev/TagStudio

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TagStudioDev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hRNnVKhF2G
  tags:
    Upcoming Feature: upcoming

nav:
  - Home:
      - index.md
  - Getting Started:
      - install.md
      - usage.md
      - Developing:
        - developing.md
        - contributing.md
        - style.md
      - Help:
          - help/ffmpeg.md
  - Library:
      - library.md
      - entries.md
      - preview_support.md
      - search.md
      - ignore.md
      - macros.md
      - Fields:
        - fields.md
      - Tags:
          - tags.md
          - colors.md
  - Updates:
      - changelog.md
      - roadmap.md
      - library_changes.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto-outline
        name: Switch to Light Mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/lightbulb-night-outline
        name: Switch to System Preference
  logo: assets/icon_mono.svg
  favicon: assets/icon.ico
  font:
    code: Jetbrains Mono
  language: en
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
  icon:
    repo: fontawesome/brands/github
    tag:
      upcoming: material/flask-outline

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

plugins:
  - search
  - tags
  - social:  # social embed cards
      enabled: !ENV [CI, false]  # enabled only when running in CI (eg GitHub Actions)

extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=Bai+Jamjuree:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&display=swap
