name: MyPy

on: [ push, pull_request ]


jobs:
  mypy:
    name: Run MyPy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          # pyside 6.6.3 has some issue in their .pyi files
          pip install PySide6==6.6.2
          pip install -r requirements.txt
          pip install mypy==1.10.0
          mkdir tagstudio/.mypy_cache

      - uses: tsuyoshicho/action-mypy@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
          workdir: tagstudio
          level: error
          mypy_flags: --config-file ../pyproject.toml
